### ISSUE TITLE
Add STATIC_URL, ASSETS_ROOT and ASSETS_URL settings.

### ISSUE THREAD

**Issue by roberkules** [jessedhillon/pyramid_scss#4]
Currently you support only the static root path:

``` python
def includeme(config):
    load_paths, static_path = _get_import_paths(config.registry.settings)
    scss.LOAD_PATHS = ','.join([scss.LOAD_PATHS, ','.join(load_paths)])
    scss.STATIC_ROOT = static_path
    config.add_renderer('scss', renderer_factory)
```

Can you also add the settings for:

scss.STATIC_URL
scss.ASSETS_ROOT
scss.ASSETS_URL

Otherwise generating sprites doesn't work at all.
Thx

**Comment by jessedhillon** [comment]
Thanks Robert. Could you provide me with some fixtures for a test case, so I can test when sprite generation is working correctly? Thanks

**Comment by jessedhillon** [comment]
You can put them in `tests/fixtures` and then issue a pull request.

**Comment by jessedhillon** [comment]
Implemented.
