### ISSUE TITLE
cache: false doesn't work

### ISSUE THREAD

**Issue by dholth** [jessedhillon/pyramid_scss#6]
Editing the scss, but the generated css stays the same with scss.cache false, pyramid.reload_(templates|assets) true. Have to restart the app to see new scss.

**Comment by tdavis** [comment]
This is actually fixed in #3, just never uploaded to pypi, sadly.

**Comment by tdavis** [comment]
For others finding this: I have (hopefully temporarily) uploaded the proper version to pypi as `pyramid_scss2`.

**Comment by jessedhillon** [comment]
Uploading to PyPI soon, thanks

**Comment by jessedhillon** [comment]
@tdavis, just FYI I've uploaded the latest source to PyPI so you can remove `pyramid_scss2` if you like. Thanks for the fix though, very sorry to have lagged on it for so long
